### ISSUE TITLE
Bugs out when also using Thandul's Togglable Effects

### ISSUE THREAD

**Issue by GambetTV** [illandril/FoundryVTT-token-hud-scale#10] opened 2021-02-02 22:30 UTC
Love the module, but it bugs out when also using Thandul's Togglable Effects module. Basically creates 2 versions of Thandul's icons, one at the normal size, and one at the scaled size from Illandril's module. Not sure which module is causing the error so I'm posting this to both modules, but I suspect the problem originates with your module, as even when using the standard icons you can see the normal sized one popping in, then getting deleted before the resized version pops in.

**Comment by kszczepanskidev** [comment] 2021-02-02 22:43
For the [Thandul's Togglable Effect](https://github.com/krysztalzg/ThandulsTogglableEffects/issues/8) module it's just creating new temporary effect on an actor, so my guess is that there's some issue here with when the status icon resize on the token is being called.

**Comment by illandril** [comment] 2021-02-02 23:15
I cannot reproduce this issue (the flicker of a normal size icon before it is quickly replaced by the resized version I do see - this was previously necessary to correct an issue in earlier versions of Foundry but it looks like I might be able to remove it now - this will be resolved as issue #11 once I have time to test a fix).

Can you please provide me with...
1. A list of all modules (including the versions) you have active (including both Illandril's Token HUD Scaler and Thandul's Togglable Effects)
2. The version of Foundry you are using
3. The name and version of the system you are using
4. The name and version of the browser you are using
5. A screenshot of the issue
6. The output of the following commands, executed in your browser's javascript console (or the Foundry App's console - press F12 to open the dev tools) after selecting the token shown in the screenshot: 
```
JSON.stringify(_token.data.effects,null,2);
JSON.stringify((_token.actor && _token.actor.temporaryEffects) || [], null, 2)
```

**Comment by kszczepanskidev** [comment] 2021-02-02 23:25
As I'm able to replicate this issue here's few data from my case:
1. Active modules
```
about-time--v0.1.62;
dae--v0.2.42;
illandril-token-hud-scale--v1.1.0;
lib-wrapper--v1.3.5.0;
ThandulsTogglableEffects--v1.2.5;
tidy5e-sheet--v0.4.13;
tidy-ui_game-settings--v0.1.21;
times-up--v0.1.2;
```
2. Foundry 0.7.9
3. DnD 5e 1.2.4
4. Foundry launcher
5.  
https://user-images.githubusercontent.com/6009785/106675513-83397980-65b5-11eb-9513-59aee40967bd.mp4

6. First commands returns empty array, second this:
[JSON.stringify.txt](https://github.com/illandril/FoundryVTT-token-hud-scale/files/5915012/JSON.stringify.txt)

**Comment by illandril** [comment] 2021-02-02 23:41
That shows the flicker issue (which I split off into issue #11), not the duplicate icon issue (unless I'm misunderstanding @GambetTV and there isn't a duplicate icon issue, only the flickering issue).

**Comment by GambetTV** [comment] 2021-02-03 10:41
Apologies, I've been downloading so many modules and I don't seem to be able to duplicate the issue anymore. I can tell you that I had the scaler set to 3, which made them bigger. I think it defaults to 4 though, right? What it looked like to me at the time was that when the first status marker you used was one from Thandul's, it would create two versions of it, a larger one at size 3, and a smaller one at the default size 4. IIRC untoggling it and retoggling it fixed it, but I'd experience it with every new token.

If I used one of the default status icons, and then used one from Thandul's, it would put one below the original icon, and one next to it. I did have it set up to go to the right rather than downward.

I don't have version numbers anymore, but everything was up to date, and I used "Find the culprit!" to reduce my mod list to just those two and I was still getting the issue. I've since downloaded a few other modules that deal with the status effects and while I still see the flickering, I can't seem to duplicate it, so I apologize that I can't be more help.

I'm completely up to date on Foundry, D&D5e, and all my mods. I even manually went through and deleted/redownloaded everything prior to experiencing this issue so I'm certain I was up to date. Hope that helps somewhat!

**Comment by illandril** [comment] 2021-02-03 14:39
Not having the problem is the ultimate goal, so it being fixed without explanation is better than it being broken without being able to figure out why (though not as good as know what broke it and having a proper, permanent fix in place so it never happens again). I'll do some more testing to see if I can find a way to trigger the issue while I test the fix for the flickering. If you happen to see it again, try to capture that information I asked for (and anything else you think might be helpful in reproducing the issue).

**Comment by illandril** [comment] 2021-02-27 02:35
I'm closing this under the assumption that the other changes I've made to this module have stopped this issue from appearing anymore. If you can reproduce it again, provide the information in my first comment up top and I'll look into this again.

**Closed as completed by illandril** 2021-02-27 02:35 UTC
Labels: compatibility issue
